# Einstein-de Sitter cosmology.
# Values follow Pavlidou & Fields, PRD 71 043510 (2005), p. 7.
Omega_m: 1.0
Omega_L: 0.0       # no dark energy
s_8: 0.45          # density-field variance normalisation at the 8 Mpc/h scale
m_8: 8.0e14        # mass scale associated with s_8 [solar masses]
delta_c: 1.6865    # collapse overdensity
